#!/bin/sh

#
# (c) 2025 Cezary Jackiewicz <cezary@eko.one.pl>
#

BASEPATH="/tmp/apcontroller"

. /lib/functions.sh
. /usr/share/libubox/jshn.sh

show_data_from_host() {
	local cfg="$1"
	local oldns
	local hostname model load uptime mac software ssid

	config_get_bool enabled "$cfg" enabled 1
	config_get name "$cfg" name
	config_get ipaddr "$cfg" ipaddr
	config_get port "$cfg" port 22
	config_get username "$cfg" username
	config_get password "$cfg" password

	json_add_object
	json_add_string "section" "$cfg"
	json_add_boolean "enabled" "$enabled"
	json_add_string "name" "$name"
	json_add_string "ipaddr" "$ipaddr"
	json_add_int "port" "$port"
	json_add_string "username" "$username"
	json_add_string "password" "$password"

	LASTCONTACT=-1
	if [ -s "${BASEPATH}/${ipaddr}-${cfg}" ]; then
		FILEMODTIME=$(date +%s -r $BASEPATH/${ipaddr}-${cfg})
		NOW=$(date +%s)
		LASTCONTACT=$((NOW - FILEMODTIME))

		json_set_namespace host oldns
		json_init
		json_load_file "${BASEPATH}/${ipaddr}-${cfg}"
		json_get_vars hostname model load uptime mac software ssid channels2g channels5g channels6g

		for BAND in 2g 5g 6g; do
			if json_is_a "clientslist${BAND}" array; then
				json_set_namespace $oldns
				json_add_array "clientslist${BAND}"
				json_set_namespace host oldns

				json_select "clientslist${BAND}"

				idx=1
				while json_is_a $idx object; do
					json_select $idx
					json_get_var _ssid "ssid"
					json_get_var _mac "mac"
					json_get_var _rx "rx"
					json_get_var _tx "tx"
					json_get_var _signal "signal"
					json_get_var _connected "connected"
					json_get_var _wifi "wifi"
					json_get_var _ipaddr "ipaddr"
					json_get_var _name "name"

					json_set_namespace $oldns
					json_add_object
					json_add_string "ssid" "$_ssid"
					json_add_string "mac" "$_mac"
					json_add_int "rx" "$_rx"
					json_add_int "tx" "$_tx"
					json_add_int "signal" "$_signal"
					json_add_int "connected" "$_connected"
					json_add_int "wifi" "$_wifi"
					json_add_string "ipaddr" "$_ipaddr"
					json_add_string "name" "$_name"
					json_close_object
					json_set_namespace host oldns

					json_select ..
					idx=$(( idx + 1 ))
				done

				json_set_namespace $oldns
				json_close_array
				json_set_namespace host oldns

				json_select ..
			fi
		done

		json_cleanup
		json_set_namespace $oldns

		json_add_string "hostname" "$hostname"
		json_add_string "model" "$model"
		json_add_string "load" "$load"
		json_add_int "uptime" "$uptime"
		json_add_string "mac" "$mac"
		json_add_string "software" "$software"
		[ -n "$channels2g" ] && json_add_string "channels2g" "$channels2g"
		[ -n "$channels5g" ] && json_add_string "channels5g" "$channels5g"
		[ -n "$channels6g" ] && json_add_string "channels6g" "$channels6g"
	fi
	json_add_int "lastcontact" "$LASTCONTACT"

	json_close_object
}

show_status() {
	config_load apcontroller
	json_init
	json_add_array "hosts"
	config_foreach show_data_from_host host
	json_close_array
	json_dump
}

case "$1" in
	list)
		json_init
		json_add_object "status"
		json_close_object
		json_dump
	;;
	call)
		case "$2" in
			status)
				show_status
				;;
		esac
	;;
esac

exit 0
