#!/bin/sh

MIN=$(uci -q get apcontroller.@global[0].interval)
touch /etc/crontabs/root
grep -q apcontroller /etc/crontabs/root || echo "*/${MIN:-5} * * * * /usr/bin/apcontroller" >> /etc/crontabs/root

T=$(uci -q get apcontroller.@global[0].path)
if [ -z "$T" ]; then
	uci set apcontroller.@global[0].path="/tmp/apcontroller"
	uci commit apcontroller
fi

exit 0
