#!/bin/sh

MIN=$(uci -q get apcontroller.@global[0].interval)
touch /etc/crontabs/root
grep -q apcontroller /etc/crontabs/root || echo "*/${MIN:-5} * * * * /usr/bin/apcontroller" >> /etc/crontabs/root

exit 0
